services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - frappe_network
    restart: unless-stopped

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - frappe_network
    restart: unless-stopped

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: unless-stopped

  redis-queue:
    image: redis:6.2-alpine
    volumes:
      - redis-queue-data:/data
    networks:
      - frappe_network
    restart: unless-stopped

  backend:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe_network
    restart: unless-stopped

  create-site:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    depends_on:
      - db
      - redis-cache
      - redis-queue
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      SOCKETIO_PORT: ${SOCKETIO_PORT}
      FRAPPE_SITE_NAME: ${FRAPPE_SITE_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint: bash
    command: >
      wait-for-it ${DB_HOST}:${DB_PORT} -t 60 &&
      wait-for-it ${REDIS_CACHE} -t 60 &&
      wait-for-it ${REDIS_QUEUE} -t 60 &&
      if [ ! -d "/home/frappe/frappe-bench/sites/${FRAPPE_SITE_NAME}" ]; then
        bench new-site ${FRAPPE_SITE_NAME} --mariadb-root-username root --mariadb-root-password ${MYSQL_ROOT_PASSWORD} --admin-password ${ADMIN_PASSWORD} --install-app erpnext --set-default;
      fi
    networks:
      - frappe_network
    restart: "no"

  frontend:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    depends_on:
      - backend
      - websocket
      - create-site
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER}
      SOCKETIO: websocket:${SOCKETIO_PORT}
      NGINX_ENFORCE_TRAEFIK: "true"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erpnext.rule=Host(`${FRAPPE_SITE_NAME}`)"
      - "traefik.http.routers.erpnext.entrypoints=websecure"
      - "traefik.http.routers.erpnext.tls.certresolver=myresolver"
    networks:
      - frappe_network
    restart: unless-stopped

  websocket:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    environment:
      FRAPPE_REDIS_CACHE: ${REDIS_CACHE}
      FRAPPE_REDIS_QUEUE: ${REDIS_QUEUE}
    command: node /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe_network
    restart: unless-stopped

  queue-long:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    command: bench worker --queue long,default,short
    environment:
      FRAPPE_REDIS_CACHE: ${REDIS_CACHE}
      FRAPPE_REDIS_QUEUE: ${REDIS_QUEUE}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe_network
    restart: unless-stopped

  queue-short:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    command: bench worker --queue short,default
    environment:
      FRAPPE_REDIS_CACHE: ${REDIS_CACHE}
      FRAPPE_REDIS_QUEUE: ${REDIS_QUEUE}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe_network
    restart: unless-stopped

  scheduler:
    image: frappe/erpnext:${ERPNEXT_VERSION}
    command: bench schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    networks:
      - frappe_network
    restart: unless-stopped

volumes:
  db-data:
  redis-queue-data:
  sites:
  logs:
  letsencrypt:

networks:
  frappe_network:
    driver: bridge
